# .github/workflows/ci_pipeline.yml
# Self-healing CI: This workflow lints, formats, tests, and auto-commits fixes.

name: Neurodiagnoses CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-format-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Give the job permission to write back to the repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Formatters to Fix Code
        run: |
          ruff format .
          ruff check . --fix

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: Auto-apply formatting and linting fixes"
          branch: ${{ github.head_ref || github.ref_name }}
      
      - name: Run Quality Checks (Verification)
        run: |
          echo "Verifying code quality after auto-formatting..."
          black --check .
          ruff check .

      - name: Run tests with pytest
        run: |
          export PYTHONPATH=$PWD
          pytest
