name: Data Integration Workflow

on:
  schedule:
    # This schedule runs the workflow once per day at 00:00 UTC.
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-data-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          # If you have additional dependencies, add them here.
          # For example: pip install pandas

      - name: Run MIP Integration Script
        env:
          EBRAINS_API_KEY: ${{ secrets.EBRAINS_API_KEY }}
        run: |
          python data_integration/mip_integration.py

      - name: List Output Files
        run: ls -l
